image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - haskell.haskell@1.2.0:ZPrUKYpwCCFQf9Q0phszuQ==