image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'
vscode:
  extensions:
    - haskell.haskell@1.2.0:ZPrUKYpwCCFQf9Q0phszuQ==
    - justusadam.language-haskell@3.3.0:uqgpHstOoamig+7LyFNNVw==
    - gattytto.phoityne-vscode@0.0.29:zDRfEpZhRUCw1C9afPQ94g==